### ISSUE TITLE
Data not shown

### ISSUE THREAD

**Issue by injcristianrojas** [OWASP/railsgoat#216] opened 2016-01-07 18:12 UTC
I can't see any data when navigating through pages. Only when I refresh manually I can see the users list, for instance. I'm sending over a screenshot of the situation with a lot of typeErrors. I use Firefox 43 and Chrome 47 on Linux.

![screenshot from 2016-01-07 15-09-48](https://cloud.githubusercontent.com/assets/862690/12178561/e1478b18-b550-11e5-9e69-b035d9332673.png)

**Comment by cktricky** [comment] 2016-01-07 18:32
I have an idea of what is wrong, let's see what we can do to resolve.

**Comment by jasnow** [comment] 2016-01-07 18:34
@cktricky - Found that when I click on PTO (left side) - we get error page. Sending fix.

**Comment by cktricky** [comment] 2016-01-07 18:41
Looks like a call to populate the charts is causing the problem @jasnow

**Comment by cktricky** [comment] 2016-01-07 20:03
@injcristianrojas We will post a solution soon, in the meantime, you should be able to hit refresh from that screen and still have the table populated. Unfortunately, the root cause (I suspect) is how we are loading the partial - so a simple refresh (just to get you through what you're working on) should fix it until I can clean this up.

**Comment by injcristianrojas** [comment] 2016-01-07 20:06
@cktricky that's what I've been doing so far. Thank you for the quick responses and let me know when it's fixed, so I can close this issue real quick.

**Comment by cktricky** [comment] 2016-01-07 20:21
@injcristianrojas Should be fixed now, please `git pull origin master` and give it a spin.

**Closed** 2016-01-07 20:20 UTC
Labels: bug

**Comment by injcristianrojas** [comment] 2016-01-07 20:32
@cktricky The users list works, but the font size button has the same issue (push, then manually refresh for it to work)

**Comment by cktricky** [comment] 2016-01-07 20:41
I'm curious if that is just the way that always worked (the font button). Think @mccabe615 might have built it, so please chime in Mike.
